chore: support absolute caching path
buildkite-plugins/cache-buildkite-plugin pull request #83
Opened 2024-10-10 08:47 UTC by peter-svensson

Some solutions (pre-commit being one example) requires the cached content to be extracted to the same location to work.
Since the build path most likely change for every build in CI, there is a need to store the cached content in a different location on the file system.
The current version of the cache plugin strips leading `/` when compressing and will always extract to the current working directory. So even though it is possible to set an absolute path the behaviour is not the expected one.
This PR allows for absolute caching path (like `/tmp/cache`)

2024-10-21 19:23 UTC, toote requested changes
awesome contribution! A few comments here and there as to code styling and where tests should be but it is 90% of the way there :)

2024-10-21 19:23 UTC, toote commented on lib/compression.bash
> +    fi
In order to avoid having two code paths that execute `tar` I think it may be a better idea to have the options as a variable instead. Something like:

```suggestion
    TAR_OPTS='cz'

    if is_absolute_path "${COMPRESSED_FILE}"; then
      TAR_OPTS="${TAR_OPTS}"P
    fi
    
    tar "${TAR_OPTS}"f "${FILE}" "${COMPRESSED_FILE}"
```

While not a deal breaker, it ensures that if we need to change how `tar` is executed in the future, there is a single place to do so.

2024-10-21 19:23 UTC, toote commented on lib/compression.bash
> +      mv "${COMPRESS_DIR}/${FILE}.zip" "${FILE}"
I think that this code is really noisy for something that should be quite simple. The `echo` doesn't provide any critical information to the operation of the plugin, the `|| exit 1` are unnecessary because of the `-e` option of the hooks themselves and I believe it is cleaner to use sub-shells instead of `pushd/popd`.

What do you think of something like the following?

```suggestion
      ( # subshell to avoid chaging the working directory
        cd "${COMPRESS_DIR}"
        # because ZIP complains if the file does not end with .zip
        zip -r "${FILE}.zip" "${COMPRESSED_FILE}"
        mv "${FILE}.zip" "${FILE}"
      )
```

2024-10-21 19:23 UTC, toote commented on lib/compression.bash
> +    fi
same here:

```suggestion
    TAR_OPTS='xz'
    if is_absolute_path "${COMPRESSED_FILE}"; then
      TAR_OPTS="${TAR_OPTS}"P
    fi
    
    tar "${TAR_OPTS}"f "${FILE}"
```

2024-10-21 19:23 UTC, toote commented on lib/compression.bash
> +      popd || exit 1
same here:

```suggestion
      mkdir -p "${RESTORE_DIR}"
      mv "${FILE}" "${RESTORE_DIR}/${FILE}.zip"
      ( # subshell to avoid changing working directory
        cd "${RESTORE_DIR}"
        unzip -o "${FILE}.zip"
        rm "${FILE}.zip"
      )
```

2024-10-21 19:23 UTC, toote commented on tests/compression-tgz.bats
Excellent initiative to isolate these tests... though I do not think they are named appropriately. Compression itself is being tested in `post-checkout-{tgz,zip}.bats`, this file (and the other one) are just testing absolute path compression on both instanaces.

I'd rather you just fold these tests into their corresponding test files.

2024-10-21 19:23 UTC, toote commented on tests/compression-zip.bats
Excellent initiative to isolate these tests... though I do not think they are named appropriately. Compression itself is being tested in `post-checkout-{tgz,zip}.bats`, this file (and the other one) are just testing absolute path compression on both instanaces.

I'd rather you just fold these tests into their corresponding test files.

2024-10-21 19:23 UTC, toote commented on tests/post-checkout-zip.bats
> +    "-o \* \* : echo uncompressed \$2 into \$3"
good catch

2024-10-21 19:23 UTC, toote commented on tests/post-checkout-zip.bats
> +    "get \* \* : mkdir -p $(dirname \$3) && touch \$3 && echo restoring \$2 to \$3"
why is this change necessary if you are not changing any existing behaviour?

2024-10-23 14:02 UTC, peter-svensson commented on lib/compression.bash
> +    fi
Sounds reasonable and sound in every way 😊

2024-10-23 14:31 UTC, peter-svensson commented on tests/post-checkout-zip.bats
> +    "get \* \* : mkdir -p $(dirname \$3) && touch \$3 && echo restoring \$2 to \$3"
Could be leftover from tests, let me double-check if it's necessary (sounds bad if it is 😊)

2024-10-23 21:05 UTC, toote reviewed
It was perfect @peter-svensson ... except for a test that does not do what it is supposed to do.

Note that only the test thing is important, all other comments I left are aesthetics and I would approve this even without addressing them

2024-10-23 21:05 UTC, toote commented on tests/post-checkout-zip.bats
> +}
This is not actually testing absolute paths  as it is not overriding the `BUILDKITE_PLUGIN_CACHE_PATH` variable

2024-10-23 21:05 UTC, toote commented on tests/post-command-tgz.bats
> -    "czf \* \* : echo compressed \$2 into \$3"
you could instead change this to:

```
stub tar "\* \* \* : echo compressed \$2 into \$3 with options \$1"
```

and it would still be valid for all tests and you could then ensure that the options were passed correctly

2024-10-23 21:05 UTC, toote commented on tests/post-command-zip.bats
> +  export BUILDKITE_PLUGIN_CACHE_PATH=/tmp/tests/data/my_files
while I am not against this version, it may be a better idea to not hardcode this path and instead use `mktemp` to create a folder wherever the system sees fit instead:

```suggestion
  mkdir -p /tmp/tests/data/my_files
  export BUILDKITE_PLUGIN_CACHE_PATH="$(mktemp -d)"
```

obviously, removing it after running as you already do as well

2024-10-23 21:52 UTC, peter-svensson commented on tests/post-command-tgz.bats
> -    "czf \* \* : echo compressed \$2 into \$3"
Neat! 👍

2024-10-23 21:52 UTC, peter-svensson commented on tests/post-checkout-zip.bats
> +}
Good catch! Must have been tired 😊

2024-10-23 21:53 UTC, peter-svensson commented
> It was perfect @peter-svensson ... except for a test that does not do what it is supposed to do.
> 
> Note that only the test thing is important, all other comments I left are aesthetics and I would approve this even without addressing them

No worries I'll fix them up. 
Great review comments by the way!

2024-10-25 05:50 UTC, toote approved these changes
:clap: 

Just a minor comment... and if you still feel like indulging in my nitpicking, feel free to update the README examples to the next version `v1.3.0` to have the linter step of the pipeline not fail

2024-10-25 05:50 UTC, toote commented on tests/post-command-tgz.bats
> +}
You forgot to remove the created folder:

```suggestion
  assert_output --partial "with options czPf"
  
  rm -rf "${BUILDKITE_PLUGIN_CACHE_PATH}"
}
```

2024-10-25 20:00 UTC, merged